spring.application.name=tempoServiceApplication
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tempoDb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.org.hibernate=WARN
logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=ERROR

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
